name: Build Android
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: |
          chmod +x gradlew || true
          ls -la
      - name: Build with Gradle
        run: |
          if [ -f "gradlew" ]; then
            ./gradlew assembleDebug
          else
            gradle wrapper --gradle-version=8.0
            ./gradlew assembleDebug
          fi
      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk
